---
- name: (NGINX) Set and sanitize facts
  set_fact:
    nginx_daemon: >-
      {{ nginx_daemon
      if nginx_daemon is defined
      and nginx_daemon is string
      and nginx_daemon != 0
      else "nginx" }}

- name: (RedHat) Handle errata
  set_fact:
    apache_daemon: httpd
  when:
    - ansible_os_family == "RedHat"
    - apache_daemon is undefined

- name: (Debian) Handle errata
  set_fact:
    apache_daemon: apache2
  when:
    - ansible_os_family == "Debian"
    - apache_daemon is undefined

- name: (Debian) Handle errata
  set_fact:
    nginx_ssl_protocols:
      - TLSv1.2
  when: >-
    (ansible_distribution == "Ubuntu"
    and ansible_distribution_version is version('16.04', '=='))
    or
    (ansible_distribution == "Debian"
    and ansible_distribution_version is version('9', '=='))
