---

- name: (Python 3) Install SELinux management packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - libselinux-python3
    - policycoreutils-python3
    - libsemanage-python3
  when: ansible_python_version is version('3.0', '>=')

- name: (Python 2) Install SELinux management packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - libselinux-python
    - policycoreutils-python
    - libsemanage-python
  when: ansible_python_version is version('3.0', '<')

- name: Enable SELinux
  ansible.posix.selinux:
    policy: targeted
    state: enforcing

- name: Register file context for site cache
  community.general.sefcontext:
    target: "/var/nginx/cache/{{ nginx_cache_name }}(/.*)?"
    setype: httpd_cache_t
    state: present
  register: filecontext_sitecache

- name: Run restore context to site cache
  command: "restorecon -Rv /var/nginx/cache/{{ nginx_cache_name }}"
  when: filecontext_sitecache.changed

- name: Set SELinux booleans
  ansible.posix.seboolean:
    name: "{{ item }}"
    state: yes
    persistent: yes
  with_items: "{{ selinux_booleans }}"
