---

- name: Enable SELinux
  ansible.posix.selinux:
    policy: targeted
    state: enforcing

- name: Install SELinux management packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - libselinux-python3
    - policycoreutils-python3
    - libsemanage-python3

- name: httpd_cache_t sitecache
  community.general.sefcontext:
    target: "/var/nginx/cache/{{ nginx_cache_name }}(/.*)?"
    setype: httpd_cache_t
    state: present
  when: selinux

- name: Run restore context to site cache
  command: "restorecon -Rv /var/nginx/cache/{{ nginx_cache_name }}"

- name: Set httpd_execmem
  ansible.posix.seboolean:
    name: httpd_execmem
    state: yes
    persistent: yes
  with_items:
    - httpd_setrlimit
    - httpd_execmem
    - httpd_can_network_connect
    - httpd_can_network_connect_db
    - httpd_read_user_content
